import { useEffect, useRef, useState } from 'react';
import { animatedSkylineSvg, staticSkylineSvg } from './norleaseSkylineMarkup';

// The actual artwork (SVG defs, gradients, ~120 batched shapes, pins, arcs)
// is procedurally generated by scripts/generate-skyline.mjs and checked in
// as components/norleaseSkylineMarkup.ts. This component just injects the
// right pre-built variant and wires up the two runtime behaviors that can't
// be baked into a static string: honoring prefers-reduced-motion before the
// animated markup ever mounts, and pausing SMIL animations while the card
// is off-screen.
export default function NorleaseSkyline() {
  const containerRef = useRef<HTMLDivElement>(null);
  const [reducedMotion, setReducedMotion] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    setReducedMotion(mq.matches);
    const onChange = () => setReducedMotion(mq.matches);
    mq.addEventListener('change', onChange);
    return () => mq.removeEventListener('change', onChange);
  }, []);

  const active = mounted && !reducedMotion;

  useEffect(() => {
    if (!active) return;
    const container = containerRef.current;
    const svg = container?.querySelector('svg') as SVGSVGElement | null;
    if (!svg || typeof svg.pauseAnimations !== 'function') return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) svg.unpauseAnimations();
        else svg.pauseAnimations();
      },
      { threshold: 0.1 }
    );
    observer.observe(svg);
    return () => observer.disconnect();
  }, [active]);

  return (
    <div
      ref={containerRef}
      style={{ width: '100%', height: '100%' }}
      dangerouslySetInnerHTML={{ __html: active ? animatedSkylineSvg : staticSkylineSvg }}
    />
  );
}
